---
spring:
  application:
    name: spring-cloud-eureka-ha1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
#      defaultZone: http://peer2:8762/eureka/
       defaultZone: http://localhost:8762/eureka/
---
spring:
  application:
    name: spring-cloud-eureka-ha2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/
